spring.application.name=student-armory-backend
server.port=${PORT:8080}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,http://localhost:5174,http://127.0.0.1:5173,https://*}

# ApyHub API Configuration
apyhub.base-url=https://api.eu.apyhub.com
apyhub.token=${APYHUB_API_KEY:80ba68401961d4d54aef1b1ad304f93819acbc3adff849b31c8900383a6e0e03}

# Multipart File Upload Configurations (Up to 100MB as supported by ApyHub)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
